from django.contrib import admin
from django.urls import path
from core.web_views import dashboard_page, login_page
from core.views import (
    auth_login,
    auth_me,
    auth_logout,
    activities_collection,
    activity_update,
    activity_assignments,
    activity_assignment_create,
    activity_assignment_update,
    beneficiaries_collection,
    beneficiary_archive,
    beneficiary_update,
    disability_assessments_collection,
    disability_assessment_update,
    home_visit_update,
    home_visits_collection,
    referrals_collection,
    referral_submit,
    referral_follow_ups_collection,
    projects_collection,
    projects_detail_collection,
    dashboard_activity_status_summary,
    dashboard_financial_summary,
    dashboard_summary,
    poultry_group_create,
    poultry_groups_list,
    poultry_group_update,
    poultry_stock_movement_update,
    egg_production_update,
    feed_record_update,
    poultry_health_record_update,
    poultry_sale_update,
    poultry_stock_movement_create,
    poultry_stock_movements_list,
    egg_production_create,
    egg_production_list,
    feed_record_create,
    feed_records_list,
    poultry_health_record_create,
    poultry_health_records_list,
    poultry_sale_create,
    poultry_sales_list,
    farm_crop_create,
    farm_crop_update,
    farm_activity_update,
    harvest_update,
    farm_poultry_transfer_update,
    farm_crops_list,
    farm_activity_create,
    farm_activities_list,
    harvest_create,
    harvests_list,
    financial_transaction_create,
    financial_transactions_list,
    financial_transaction_update,
    me_indicators_summary,
    me_indicators_list,
    me_indicator_create,
    me_indicator_update,
    me_indicator_delete,
    me_indicator_records_list,
    me_indicator_record_create,
    me_indicator_record_update,
    me_indicator_record_delete,
    farm_poultry_transfer_create,
    farm_poultry_transfers_list,
    project_assignments,
    project_assignment_create,
    project_assignment_update,
)
from core.referral_workflow import referral_approve

urlpatterns = [
    path("admin/", admin.site.urls),
    path("login/", login_page),
    path("dashboard/", dashboard_page),
    path("auth/login/", auth_login),
    path("auth/me/", auth_me),
    path("auth/logout/", auth_logout),
    path("dashboard/summary/", dashboard_summary),
    path(
        "dashboard/activity-status-summary/",
        dashboard_activity_status_summary,
    ),
    path(
        "dashboard/financial-summary/",
        dashboard_financial_summary,
    ),
    path("activities/", activities_collection),
    path(
        "activities/<int:activity_id>/",
        activity_update,
    ),
    path(
        "activities/<int:activity_id>/assignments/",
        activity_assignments,
    ),
    path(
        "activities/<int:activity_id>/assignments/create/",
        activity_assignment_create,
    ),
    path(
        "activities/<int:activity_id>/assignments/<int:assignment_id>/",
        activity_assignment_update,
    ),
    path("projects/", projects_collection),
    path("poultry-groups/", poultry_groups_list),
    path("poultry-groups/create/", poultry_group_create),
    path("poultry-groups/<int:group_id>/", poultry_group_update),
    path("poultry-stock-movements/", poultry_stock_movements_list),
    path("poultry-stock-movements/create/", poultry_stock_movement_create),
    path("poultry-stock-movements/<int:movement_id>/", poultry_stock_movement_update),
    path("egg-production/", egg_production_list),
    path("egg-production/create/", egg_production_create),
    path("egg-production/<int:egg_production_id>/", egg_production_update),
    path("feed-records/", feed_records_list),
    path("feed-records/create/", feed_record_create),
    path("feed-records/<int:feed_record_id>/", feed_record_update),
    path("poultry-health-records/", poultry_health_records_list),
    path("poultry-health-records/create/", poultry_health_record_create),
    path("poultry-health-records/<int:health_record_id>/", poultry_health_record_update),
    path("poultry-sales/", poultry_sales_list),
    path("poultry-sales/create/", poultry_sale_create),
    path("poultry-sales/<int:poultry_sale_id>/", poultry_sale_update),
    path("farm-crops/", farm_crops_list),
    path("farm-crops/create/", farm_crop_create),
    path("farm-crops/<int:crop_id>/", farm_crop_update),
    path("farm-activities/", farm_activities_list),
    path("farm-activities/create/", farm_activity_create),
    path("farm-activities/<int:farm_activity_id>/", farm_activity_update),
    path("harvests/", harvests_list),
    path("harvests/create/", harvest_create),
    path("harvests/<int:harvest_id>/", harvest_update),
    path("financial-transactions/", financial_transactions_list),
    path("financial-transactions/create/", financial_transaction_create),
    path("financial-transactions/<int:transaction_id>/", financial_transaction_update),
    path("me-indicators/summary/", me_indicators_summary),
    path("me-indicators/", me_indicators_list),
    path("me-indicators/create/", me_indicator_create),
    path(
        "me-indicators/<int:indicator_id>/update/",
        me_indicator_update,
    ),
    path(
        "me-indicators/<int:indicator_id>/delete/",
        me_indicator_delete,
    ),
    path("me-indicator-records/", me_indicator_records_list),
    path("me-indicator-records/create/", me_indicator_record_create),
    path(
        "me-indicator-records/<int:indicator_record_id>/update/",
        me_indicator_record_update,
    ),
    path(
        "me-indicator-records/<int:indicator_record_id>/delete/",
        me_indicator_record_delete,
    ),
    path("farm-poultry-transfers/", farm_poultry_transfers_list),
    path("farm-poultry-transfers/create/", farm_poultry_transfer_create),
    path("farm-poultry-transfers/<int:transfer_id>/", farm_poultry_transfer_update),
    path("beneficiaries/", beneficiaries_collection),
    path(
        "beneficiaries/<int:beneficiary_id>/",
        beneficiary_update,
    ),
    path(
        "beneficiaries/<int:beneficiary_id>/archive/",
        beneficiary_archive,
    ),
    path(
        "disability-assessments/",
        disability_assessments_collection,
    ),
    path(
        "disability-assessments/<int:assessment_id>/",
        disability_assessment_update,
    ),
    path(
        "home-visits/",
        home_visits_collection,
    ),
    path(
        "home-visits/<int:home_visit_id>/",
        home_visit_update,
    ),
    path(
        "referrals/",
        referrals_collection,
    ),
    path(
        "referrals/<int:referral_id>/follow-ups/",
        referral_follow_ups_collection,
    ),
    path(
        "referrals/<int:referral_id>/submit/",
        referral_submit,
    ),
    path(
        "referrals/<int:referral_id>/approve/",
        referral_approve,
    ),
    path("projects/<int:project_id>/", projects_detail_collection),
    path(
        "projects/<int:project_id>/assignments/",
        project_assignments,
    ),
    path(
        "projects/<int:project_id>/assignments/create/",
        project_assignment_create,
    ),
    path(
        "projects/<int:project_id>/assignments/<int:assignment_id>/",
        project_assignment_update,
    ),
]
