PERMISSION_VIEW = "VIEW"
PERMISSION_ADD = "ADD"
PERMISSION_EDIT = "EDIT"
PERMISSION_DELETE = "DELETE"
PERMISSION_APPROVE = "APPROVE"
PERMISSION_EXPORT = "EXPORT"
PERMISSION_MANAGE = "MANAGE"
PERMISSION_ADMINISTER = "ADMINISTER"


PERMISSIONS = {
    PERMISSION_VIEW,
    PERMISSION_ADD,
    PERMISSION_EDIT,
    PERMISSION_DELETE,
    PERMISSION_APPROVE,
    PERMISSION_EXPORT,
    PERMISSION_MANAGE,
    PERMISSION_ADMINISTER,
}


RESPONSIBILITY_DISABILITY_SERVICES = "DISABILITY_SERVICES"
RESPONSIBILITY_BENEFICIARY_REGISTRATION = "BENEFICIARY_REGISTRATION"
RESPONSIBILITY_DISABILITY_ASSESSMENT = "DISABILITY_ASSESSMENT"
RESPONSIBILITY_HOME_VISITS = "HOME_VISITS"
RESPONSIBILITY_REFERRALS_FOLLOW_UP = "REFERRALS_FOLLOW_UP"
RESPONSIBILITY_COMMUNITY_AWARENESS = "COMMUNITY_AWARENESS"
RESPONSIBILITY_PROJECT_ACTIVITIES = "PROJECT_ACTIVITIES"
RESPONSIBILITY_POULTRY_OPERATIONS = "POULTRY_OPERATIONS"
RESPONSIBILITY_FARM_OPERATIONS = "FARM_OPERATIONS"
RESPONSIBILITY_PROJECT_COORDINATION = "PROJECT_COORDINATION"
RESPONSIBILITY_FINANCIAL_OPERATIONS = "FINANCIAL_OPERATIONS"
RESPONSIBILITY_MONITORING_EVALUATION = "MONITORING_EVALUATION"


RESPONSIBILITIES = {
    RESPONSIBILITY_DISABILITY_SERVICES,
    RESPONSIBILITY_BENEFICIARY_REGISTRATION,
    RESPONSIBILITY_DISABILITY_ASSESSMENT,
    RESPONSIBILITY_HOME_VISITS,
    RESPONSIBILITY_REFERRALS_FOLLOW_UP,
    RESPONSIBILITY_COMMUNITY_AWARENESS,
    RESPONSIBILITY_PROJECT_ACTIVITIES,
    RESPONSIBILITY_POULTRY_OPERATIONS,
    RESPONSIBILITY_FARM_OPERATIONS,
    RESPONSIBILITY_PROJECT_COORDINATION,
    RESPONSIBILITY_FINANCIAL_OPERATIONS,
    RESPONSIBILITY_MONITORING_EVALUATION,
}