from core.authorization.constants import (
    RESPONSIBILITY_BENEFICIARY_REGISTRATION,
    RESPONSIBILITY_COMMUNITY_AWARENESS,
    RESPONSIBILITY_DISABILITY_ASSESSMENT,
    RESPONSIBILITY_DISABILITY_SERVICES,
    RESPONSIBILITY_FARM_OPERATIONS,
    RESPONSIBILITY_FINANCIAL_OPERATIONS,
    RESPONSIBILITY_HOME_VISITS,
    RESPONSIBILITY_MONITORING_EVALUATION,
    RESPONSIBILITY_POULTRY_OPERATIONS,
    RESPONSIBILITY_PROJECT_ACTIVITIES,
    RESPONSIBILITY_PROJECT_COORDINATION,
    RESPONSIBILITY_REFERRALS_FOLLOW_UP,
)


TITLE_RESPONSIBILITY_ELIGIBILITY = {
    "Admin": set(),

    "Director": {
        RESPONSIBILITY_DISABILITY_SERVICES,
        RESPONSIBILITY_BENEFICIARY_REGISTRATION,
        RESPONSIBILITY_DISABILITY_ASSESSMENT,
        RESPONSIBILITY_HOME_VISITS,
        RESPONSIBILITY_REFERRALS_FOLLOW_UP,
        RESPONSIBILITY_COMMUNITY_AWARENESS,
        RESPONSIBILITY_PROJECT_ACTIVITIES,
        RESPONSIBILITY_POULTRY_OPERATIONS,
        RESPONSIBILITY_FARM_OPERATIONS,
        RESPONSIBILITY_PROJECT_COORDINATION,
        RESPONSIBILITY_FINANCIAL_OPERATIONS,
        RESPONSIBILITY_MONITORING_EVALUATION,
    },

    "Programme Coordinator": {
        RESPONSIBILITY_DISABILITY_SERVICES,
        RESPONSIBILITY_BENEFICIARY_REGISTRATION,
        RESPONSIBILITY_DISABILITY_ASSESSMENT,
        RESPONSIBILITY_HOME_VISITS,
        RESPONSIBILITY_REFERRALS_FOLLOW_UP,
        RESPONSIBILITY_COMMUNITY_AWARENESS,
        RESPONSIBILITY_PROJECT_ACTIVITIES,
        RESPONSIBILITY_POULTRY_OPERATIONS,
        RESPONSIBILITY_FARM_OPERATIONS,
        RESPONSIBILITY_PROJECT_COORDINATION,
        RESPONSIBILITY_FINANCIAL_OPERATIONS,
        RESPONSIBILITY_MONITORING_EVALUATION,
    },

    "Finance": {
        RESPONSIBILITY_FINANCIAL_OPERATIONS,
        RESPONSIBILITY_MONITORING_EVALUATION,
    },

    "Member": {
        RESPONSIBILITY_DISABILITY_SERVICES,
        RESPONSIBILITY_BENEFICIARY_REGISTRATION,
        RESPONSIBILITY_DISABILITY_ASSESSMENT,
        RESPONSIBILITY_HOME_VISITS,
        RESPONSIBILITY_REFERRALS_FOLLOW_UP,
        RESPONSIBILITY_COMMUNITY_AWARENESS,
        RESPONSIBILITY_PROJECT_ACTIVITIES,
        RESPONSIBILITY_POULTRY_OPERATIONS,
        RESPONSIBILITY_FARM_OPERATIONS,
        RESPONSIBILITY_MONITORING_EVALUATION,
    },
}


RESOURCE_RESPONSIBILITY_MAP = {
    "beneficiary": RESPONSIBILITY_BENEFICIARY_REGISTRATION,
    "beneficiaries": RESPONSIBILITY_BENEFICIARY_REGISTRATION,

    "disability_assessment": RESPONSIBILITY_DISABILITY_ASSESSMENT,
    "disability_assessments": RESPONSIBILITY_DISABILITY_ASSESSMENT,

    "home_visit": RESPONSIBILITY_HOME_VISITS,
    "home_visits": RESPONSIBILITY_HOME_VISITS,

    "referral": RESPONSIBILITY_REFERRALS_FOLLOW_UP,
    "referrals": RESPONSIBILITY_REFERRALS_FOLLOW_UP,
    "follow_up": RESPONSIBILITY_REFERRALS_FOLLOW_UP,
    "follow_ups": RESPONSIBILITY_REFERRALS_FOLLOW_UP,

    "project": RESPONSIBILITY_PROJECT_COORDINATION,
    "projects": RESPONSIBILITY_PROJECT_COORDINATION,

    "activity": RESPONSIBILITY_PROJECT_ACTIVITIES,
    "activities": RESPONSIBILITY_PROJECT_ACTIVITIES,

    "poultry_group": RESPONSIBILITY_POULTRY_OPERATIONS,
    "poultry_groups": RESPONSIBILITY_POULTRY_OPERATIONS,

    "farm": RESPONSIBILITY_FARM_OPERATIONS,
    "farms": RESPONSIBILITY_FARM_OPERATIONS,

    "financial_transaction": RESPONSIBILITY_FINANCIAL_OPERATIONS,
    "financial_transactions": RESPONSIBILITY_FINANCIAL_OPERATIONS,

    "me_indicator": RESPONSIBILITY_MONITORING_EVALUATION,
    "me_indicators": RESPONSIBILITY_MONITORING_EVALUATION,

    "disability_service": RESPONSIBILITY_DISABILITY_SERVICES,
    "disability_services": RESPONSIBILITY_DISABILITY_SERVICES,

    "community_awareness": RESPONSIBILITY_COMMUNITY_AWARENESS,
}
